language: node_js
node_js:
  # https://stackoverflow.com/a/55060832/10148424
  - "11.10.1"
script:
  - npm test
deploy:
  provider: npm
  email: v7rulnik@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    repo: kupibilet-frontend/eslint-config-kupibilet
