sudo: false
language: node_js
node_js:
- stable
script:
- npm test
notifications:
  slack:
    secure: vlSv2IUE97BAwLwgl/tiFKdBr5g+bDuXFj3RFz4GJltof70FymB0unlM8P3tAaKyBQgtGdol4omz1yd2DtoTcZ6KkVkRSBJbOVf2ZOXSxyzAF38XTLG97LcZK+0kvKDu+KxuO3fd0WGO9tM51XJ90Wxnx2QFA6MxtIQ9msuzkSn45La9IJaTv4dRSzerG3USvVJ0XFuQ3aPOLz5H1/inb9EhF7jbfaf4Pu7QkdJqEfgJIlTyb+CmXYwuvoncwvLBHjzCd9sMcwo2jhF6pmc/DSdUC/TpV3NWFAKfM9XtK1UEpkwj8eldkkBAXuN+8ZJvFwHloMRLsZn6LWZT4mbXro2dvsGejs8sYfpJl+ZFzh4/v4XberZUFk9jtXGgwBnIq7pOmS9rsQ6ARI1PM6Qh3j81/qtlnTUw/hLBVLA7PzxcBsnimFJZ2SIMaeFdiqXzwIxYxlMJvr/qFmqZNOkoWFAfhFfojYLErz6Rbapvz2tYZmWZRywPY2gZ0eHmZpLRsvLIY/qutlLMhLta0Bf+FTSoBMk+ZvWq8tihXgTffDtWzT673RlQ5IqdMxkZyD06I+qpnvaV+pmiA/OKzn2+3VEOqEkVIE2LCWg5ElwIK5+/xOEhX/5hnPoeRbEXrbexK6vzNxUlpix4rUOj5CXCfQQ/GTfu59AMLoXSuiMmTbU=
