language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: max@kupibilet.ru
  api_key:
    secure: PWsJ8OSmMxMr4rcVUJcu2uNEEY+97YzkBT3LsyMquZU2AMbXtcktkQLfk0gKYBVSfTFwF/QfZwyKo1Aa4wkxyEeoe5NKytBUP4cbZGSIy7hOEq4X+ATfoWtfJGgEm8DUJreh5CL30aLNhT0ISyM6CcShIPNHV0wGWmrJjRe5Pp4liaFSe0wZifBAMQBWfpZHMG4pYrmXBY6oIKSaCm/wO+RydzPyjR/1Popf2WG95uqEe5aOkvLF5vi8+0Kr5dbOqZZBmh90mW28V1HOam79afAEQ9da+pzdHUxrm17aAaIaO6TWRrTF4gD4AxmRtnN71lTdhXFUU9An1VmQp8SjbzIwcSdbHV8GpHcSpQIG4smQj6ktnmExuvwSxquU3TXOHsTSaFQBxab8zMueP7AIHahP5gsU0ceNT7iPWJ3dt5nVd50x/IosPnZlKzUAg3mDZU5fkxQ+VKqIlzhiDTODNleKZSr1lBG/ohd2mRtsd8Id2xsMLqh7C89GTi9jORfuN7ZQlkXdZ7q2m7TkvUfRHzLeH6v/Y/az/iCmueG7jfHCXp/9uhfZwreKnCzZ/REC7tBN74Zgz/5YP5bQgBpxDUlda+wk7JGAdMFlHL6gulObl7L1UairzYhSIHxGGw/h/WFeThQXZKndfuvtWVc5UBz+UMRJrIH7YYkysA5E21o=
  on:
    branch: master
    tags: true
    repo: kupibilet-frontend/eslint-config-kupibilet
