language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: v7rulnik@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    repo: kupibilet-frontend/eslint-config-kupibilet
